name: Push

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Run test
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Run integration tests
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: integration_tests

  build:
    needs: [test, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Build
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: build_all

      - name: Upload builds
        if: github.event.action == ''
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/*
