name: Push

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Run go mod download
        run: go mod download

      - name: Run go build
        run: go build -v ./...

      - name: Run go test
        run: |
          go test -v -coverprofile cover.out ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Build
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: build_all

      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          name: infinitedb-server
          path: build/*
