name: Tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Login to Github Docker Registry
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u lucasl0st --password-stdin
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (multiarch)
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: docker_all true

      # for some reason GHCR is extremely bugged with multiarch images, only supporting single here for now
      - name: Build and push (single arch)
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: docker_noarch true

  cleanup:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged versions from GHCR
        uses: actions/delete-package-versions@v4
        with:
          package-name: infinitedb
          package-type: container
          delete-only-untagged-versions: true
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Delete old versions from GHCR
        uses: actions/delete-package-versions@v4
        with:
          package-name: infinitedb
          package-type: container
          min-versions-to-keep: 2
          ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
          token: ${{ secrets.GHCR_TOKEN }}